name: Accessibility Audits

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: waitFor200
        with:
          site_name: "jakepartusch"
          max_timeout: 90
      - name: install required packages
        run: |
          sudo apt-get update
          sudo apt-get install libgbm-dev
          sudo apt-get install xvfb
      - name: Accessibility Audits
        run: |
          npm install -g @jakepartusch/lumberjack@0.2.0
          xvfb-run --auto-servernum lumberjack --url https://jake.partus.ch
